name: Build Docker Image CI
on: push
  # push:
    # paths:
      # - 'docker/Dockerfile'

env:
  githubUrl: docker.pkg.github.com
  imageTag: $GITHUB_REPOSITORY/$GITHUB_REPOSITORY_NAME
  version: latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: echo variables
      run: |
        echo githubUrl: $githubUrl
        echo imageTag: $imageTag
        echo version: $version
        echo {{ github.ref }}: ${{ github.ref }}
        echo {GITHUB_REF##*/}: ${GITHUB_REF##*/}
        echo {GITHUB_REF_NAME}: ${GITHUB_REF_NAME}
        echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        echo {{ env.GITHUB_REPOSITORY }}: ${{ env.GITHUB_REPOSITORY }}
        echo {{ env.GITHUB_REPOSITORY_NAME }}: ${{ env.GITHUB_REPOSITORY_NAME }}
        echo {{ github.repository }}: ${{ github.repository }}
        echo {{ github.repository.name }}: ${{ github.repository.name }}
        echo {{ github.repository }}/${{ github.repository.name }}: ${{ github.repository }}/${{ github.repository.name }}

    - name: Build Docker Image
      run: docker build -t $githubUrl/$imageTag:$version docker
    - name: docker images
      run: |
        docker images
    - name: Push Docker Image
      if: github.ref == 'master'
      run: |
        docker login $githubUrl -u publisher -p $GITHUB_TOKEN
        docker push $githubUrl/$imageTag:$version
