name: Build Docker Image CI
on: push
  # push:
    # paths:
      # - 'docker/Dockerfile'

env:
  githubUrl: docker.pkg.github.com
  branchName: ${GITHUB_REF##*/}
  testvar1: ${{github.ref}}
  testvar2: ${{github.ref_name}}
  imageTag: ${{github.repository}}/${GITHUB_REPOSITORY##*/}
  version: latest

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: echo variables
      run: |
        echo githubUrl: $githubUrl
        echo branchName: $branchName
        echo testvar1: $testvar1
        echo testvar2: $testvar2
        echo imageTag: $imageTag
        echo version: $version
        echo {{ github.ref }}: ${{ github.ref }}
        echo {GITHUB_REF##*/}: ${GITHUB_REF##*/}
        echo {GITHUB_REF_NAME}: ${GITHUB_REF_NAME}
        echo {GITHUB_REPOSITORY}: ${GITHUB_REPOSITORY}
        echo {GITHUB_REPOSITORY##*/}: ${GITHUB_REPOSITORY##*/}
        echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        echo {{ env.GITHUB_REPOSITORY }}: ${{ env.GITHUB_REPOSITORY }}
        echo {{ env.GITHUB_REPOSITORY_NAME }}: ${{ env.GITHUB_REPOSITORY_NAME }}
        echo {{ github.repository }}: ${{ github.repository }}
        echo {{ github.repository.name }}: ${{ github.repository.name }}
        echo {{ github.repository }}/${{ github.repository.name }}: ${{ github.repository }}/${{ github.repository.name }}

    - name: Build Docker Image
      run: docker build -t $githubUrl/$imageTag:$version docker
    - name: docker images
      run: |
        docker images
    - name: Push Docker Image
      # if: $branchName == 'master'
      run: |
        docker login $githubUrl -u publisher -p $GITHUB_TOKEN
        docker push $githubUrl/$imageTag:$version
