name: Build Docker Image CI
on: push
  # push:
    # paths:
      # - 'docker/Dockerfile'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - env:
        githubUrl: docker.pkg.github.com
        imageTag: $GITHUB_REPOSITORY/$GITHUB_REPOSITORY_NAME
        version: latest
      uses: actions/checkout@${{ github.ref }}

    - name: echo variables
      run: |
        echo $githubUrl
        echo $imageTag
        echo $version
        echo ${{ github.ref }}
        echo $GITHUB_REPOSITORY
        echo ${{ env.GITHUB_REPOSITORY }}
        echo ${{ github.repository }}
        echo ${{ github.repository.name }}
        echo ${{ github.repository }}/${{ github.repository.name }}

    - name: Build Docker Image
      run: docker build -t $githubUrl/$imageTag:$version docker
    - name: docker images
      run: |
        docker images
    - name: Push Docker Image
      if: github.ref == 'master'
      run: |
        docker login $githubUrl -u publisher -p $GITHUB_TOKEN
        docker push $githubUrl/$imageTag:$version
