name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: docker.pkg.github.com/blahs15/chess/chess:latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: compile
      run: |
        meson build --prefix $(pwd)/dist
        ninja -C build
